import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Features from '../components/Features'
import Downloads from '../components/Downloads'
import Faq from '../components/Faq'
import Newsletter from '../components/Newsletter'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bookmark landingpage </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <Header />
      <Hero/>
      <Features />
      <Downloads />
      <Faq />
      <Newsletter />
      <Footer />
    </div>
  )
}
